import{a as b,S as w,i as g}from"./assets/vendor-hwdYKDic.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();const P="48867408-88b49db3a4e372b4d460477c4";async function p(s,t,l){const c="https://pixabay.com",e="/api/",r=new URLSearchParams({key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:l,page:t});try{return(await b.get(c+e,{params:r})).data}catch(n){console.log("Помилка при отриманні зображень:",n)}}const q=document.querySelector(".gallery");function u(s){const t=s.map(({largeImageURL:c,webformatURL:e,tags:r,likes:n,views:f,comments:y,downloads:L})=>`<li class="gallery-item">
        <a class="gallery-link" href="${c}" >
            <img class="gallery-image" src="${e}" alt="${r}" />
            </a>
            <div class="image-info">
              <p><strong>Likes</strong> ${n}</p>
              <p><strong>Views</strong> ${f}</p>
              <p><strong>Comments</strong> ${y}</p>
              <p><strong>Downloads</strong> ${L}</p>
            </div>
          </li>`).join("");q.insertAdjacentHTML("beforeend",t),new w(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:1,showCounter:!1}).refresh()}const a={form:document.querySelector(".form"),input:document.querySelector(".input"),loader:document.querySelector("#loader"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".more-btn")};function m(){a.loader.classList.remove("hidden")}function d(){a.loader.classList.add("hidden")}function h(){a.loadMoreBtn.classList.remove("hidden")}function i(){a.loadMoreBtn.classList.add("hidden")}const o={query:"",page:1,totalHits:0,perPage:40};a.form.addEventListener("submit",async s=>{if(s.preventDefault(),o.query=s.target.elements.query.value.trim(),o.page=1,a.gallery.innerHTML="",!o.query){g.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}m(),i();try{const{hits:t,totalHits:l}=await p(o.query,o.page,o.perPage);o.totalHits=l,d(),t.length===0?(g.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i()):(u(t),t.length<o.totalHits&&h())}catch(t){d(),i(),g.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight"}),console.log("Помилка при отриманні зображень:",t)}a.form.reset()});a.loadMoreBtn.addEventListener("click",async()=>{o.page+=1,i(),m();try{const{hits:s}=await p(o.query,o.page,o.perPage);d(),s.length===0?(i(),g.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):(u(s),S(),o.page*o.perPage>=o.totalHits?(i(),g.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):h())}catch(s){d(),i(),g.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight"}),console.log("Помилка при отриманні зображень:",s)}});function S(){const t=a.gallery.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*3,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
